---
title: "Survival Analyses Exercises - Day 1"
author: Emin Onur Karakaslar
output: md_document
---


```{r warning=F, message=F}
# install.packages("haven")
# install.packages("survival")

library(haven)
library(survival)
library(survminer)
```


### Question 3 - Kaplan Meier plot
```{r Load data}
# load the data
df <- read_sav("Day 1_data set - 61162_mice.sav")

Surv(df$Time, df$Death)
```


```{r Kaplan-Meier curve}
fit.KM <- survfit(Surv(Time, Death) ~ 1, data = df)

ggsurvplot(
    fit = fit.KM, 
    xlab = "Hours", 
    ylab = "Overall survival probability", risk.table = T)
```

### Question 4 - Estimate the survival and cumulative hazard functions

```{r load drug data}
df2 <- read_sav("Day 1 - drug6mp.sav")
```
```{r min follow-up}
min(df2$timerelmp)
```

```{r max follow-up}
max(df2$timerelmp)
```
```{r KM curve}
fit.KM2 <- survfit(Surv(timerelmp, Status) ~ groups, data = df2)

ggsurvplot(
    fit = fit.KM2, 
    xlab = "Hours", 
    ylab = "Overall survival probability", risk.table = T, conf.int = T)
```
```{r}
summary(fit.KM2)
```

```{r}
ggsurvplot(
    fit = fit.KM2, 
    xlab = "Hours", 
    ylab = "Hazard ratio", risk.table = T, conf.int = T, fun = "cumhaz")
```

